version: '3'

services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rpg_enigma
      MYSQL_USER: matheo
      MYSQL_PASSWORD: matheopass
    ports:
      - 3308:3306
    volumes:
      - ${PWD}/dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1